"""Google Docs API and Local Report Export tools for Pact.

Handles creating structured Google documents, appending content,
and generating offline viewable HTML/Markdown reports in the static directory.
"""

import os
import logging
from typing import Optional

logger = logging.getLogger(__name__)

# Reports static export folder
REPORTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "static",
    "reports",
)


def create_document(
    title: str,
    sections: list[dict],
    task_id: str,
) -> str:
    """Create a Google Doc with structured sections.

    Args:
        title: Document title.
        sections: List of dicts with 'heading' and 'body' keys.
                  Example: [{"heading": "Introduction", "body": "This doc covers..."}]
        task_id: Associated task ID for tracking.

    Returns:
        Shareable Google Docs URL, or empty string on failure.
    """
    try:
        from ..utils.auth import get_docs_service

        service = get_docs_service()

        # Create the document
        doc = service.documents().create(body={"title": title}).execute()
        doc_id = doc.get("documentId", "")

        if not doc_id:
            return ""

        # Build batch update requests to add content
        requests = []
        insert_index = 1  # Start after title

        for section in reversed(sections):
            body_text = section.get("body", "")
            if body_text:
                requests.append(
                    {
                        "insertText": {
                            "location": {"index": insert_index},
                            "text": body_text + "\n\n",
                        }
                    }
                )

            heading_text = section.get("heading", "")
            if heading_text:
                requests.append(
                    {
                        "insertText": {
                            "location": {"index": insert_index},
                            "text": heading_text + "\n",
                        }
                    }
                )

        # Add PACT attribution
        requests.append(
            {
                "insertText": {
                    "location": {"index": insert_index},
                    "text": f"[Generated by PACT — Task: {task_id}]\n\n",
                }
            }
        )

        if requests:
            service.documents().batchUpdate(
                documentId=doc_id, body={"requests": requests}
            ).execute()

        # Make document link-shareable
        try:
            from googleapiclient.discovery import build
            from ..utils.auth import get_credentials

            drive_service = build("drive", "v3", credentials=get_credentials())
            drive_service.permissions().create(
                fileId=doc_id,
                body={"type": "anyone", "role": "writer"},
            ).execute()
        except Exception as e:
            logger.warning(f"Could not set sharing permissions: {e}")

        doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"
        logger.info(f"Created document: {doc_url} for task {task_id}")

        # Also write an offline local copy for immediate preview
        content_text = ""
        for sec in sections:
            content_text += f"## {sec.get('heading', '')}\n\n{sec.get('body', '')}\n\n"
        write_local_report(task_id, title, content_text)

        return doc_url

    except Exception as e:
        logger.error(f"Error creating document: {e}")
        return ""


def append_to_document(doc_url: str, content: str) -> bool:
    """Append content to an existing Google Doc."""
    try:
        from ..utils.auth import get_docs_service

        service = get_docs_service()
        doc_id = _extract_doc_id(doc_url)
        if not doc_id:
            logger.error(f"Could not extract doc ID from URL: {doc_url}")
            return False

        doc = service.documents().get(documentId=doc_id).execute()
        body = doc.get("body", {})
        end_index = body.get("content", [{}])[-1].get("endIndex", 1) - 1

        requests = [
            {
                "insertText": {
                    "location": {"index": max(end_index, 1)},
                    "text": "\n" + content,
                }
            }
        ]

        service.documents().batchUpdate(
            documentId=doc_id, body={"requests": requests}
        ).execute()

        logger.info(f"Appended content to document: {doc_id}")
        return True

    except Exception as e:
        logger.error(f"Error appending to document: {e}")
        return False


def write_local_report(task_id: str, title: str, content: str) -> dict:
    """Generate beautiful offline viewable HTML and Markdown files for the task.

    Args:
        task_id: Associated task ID.
        title: Title of the document.
        content: Main Markdown content of the report.

    Returns:
        dict: Path URLs to view the reports.
    """
    try:
        os.makedirs(REPORTS_DIR, exist_ok=True)

        # 1. Write Markdown report file
        md_filename = f"{task_id}.md"
        md_path = os.path.join(REPORTS_DIR, md_filename)
        md_text = f"# {title}\n\n[PACT Generated Offline Copy]\n\n{content}"
        with open(md_path, "w") as f:
            f.write(md_text)

        # 2. Write HTML viewable report file
        html_filename = f"{task_id}.html"
        html_path = os.path.join(REPORTS_DIR, html_filename)

        # Simple markdown-to-html conversion for sections
        html_content = ""
        lines = content.split("\n")
        for line in lines:
            line_str = line.strip()
            if line_str.startswith("## "):
                html_content += f"<h2>{line_str[3:]}</h2>"
            elif line_str.startswith("### "):
                html_content += f"<h3>{line_str[4:]}</h3>"
            elif line_str.startswith("- ") or line_str.startswith("* "):
                html_content += f"<li>{line_str[2:]}</li>"
            elif line_str:
                html_content += f"<p>{line_str}</p>"

        html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — PACT Report</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Outfit:wght@600;700&display=swap" rel="stylesheet">
    <style>
        body {{
            font-family: 'Inter', sans-serif;
            background: #090a0f;
            color: #f3f4f6;
            padding: 3rem;
            max-width: 800px;
            margin: 0 auto;
            line-height: 1.6;
        }}
        h1, h2, h3 {{
            font-family: 'Outfit', sans-serif;
            color: #fff;
            margin-top: 2rem;
            margin-bottom: 0.5rem;
        }}
        h1 {{
            border-bottom: 2px solid rgba(255, 255, 255, 0.08);
            padding-bottom: 0.75rem;
            background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }}
        h2 {{
            border-bottom: 1px solid rgba(255, 255, 255, 0.05);
            padding-bottom: 0.5rem;
        }}
        p {{
            margin-bottom: 1rem;
            color: #d1d5db;
        }}
        li {{
            margin-left: 1.5rem;
            margin-bottom: 0.5rem;
            color: #d1d5db;
        }}
        .badge {{
            display: inline-block;
            background: rgba(99, 102, 241, 0.15);
            color: #6366f1;
            padding: 0.25rem 0.75rem;
            border-radius: 99px;
            font-size: 0.8rem;
            font-weight: 500;
            margin-bottom: 1.5rem;
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="badge">PACT Generated Task Outline</div>
    {html_content}
</body>
</html>"""

        with open(html_path, "w") as f:
            f.write(html_template)

        logger.info(f"Wrote local report exports for task {task_id}")
        return {
            "md": f"/static/reports/{html_filename}",
            "html": f"/static/reports/{html_filename}",
        }
    except Exception as e:
        logger.error(f"Error writing local report files: {e}")
        return {}


def _extract_doc_id(url: str) -> str:
    """Extract Google Doc ID from a URL."""
    try:
        parts = url.split("/d/")
        if len(parts) > 1:
            return parts[1].split("/")[0]
    except Exception:
        pass
    return ""
